### PR TITLE
Improve how token field handle Backspace and highligh token

### PR DESCRIPTION
**Pull request by siuying**
Highlight token only when text field has NO text and user press backward (rather than the text field have ONE character and user press backward)

### CODE REVIEW

**Comment by PiersonBro** [comment]
Does this fix the IOS 6 token deletion bug? (Issue number 9)

**Comment by siuying** [comment]
@PiersonBro previous commits should fix #9 already

**Comment by PiersonBro** [comment]
Ah okay. I saw a crash that was related to #9, and jumped to the conclusions.

**Comment by jasarien** [comment]
merged in in a seperate pull request

**Pull request closed without merging**
